// <auto-generated />
using LanguaForge.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LanguaForge.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260722065624_EditConjTable")]
    partial class EditConjTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("LanguaForge.API.Models.Conjugation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Person")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tense")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VerbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VerbId");

                    b.ToTable("Conjugation");
                });

            modelBuilder.Entity("LanguaForge.API.Models.Verb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FrequencyRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Infinitive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIrregular")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReflexive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Verbs");
                });

            modelBuilder.Entity("LanguaForge.API.Models.Conjugation", b =>
                {
                    b.HasOne("LanguaForge.API.Models.Verb", "Verb")
                        .WithMany("Conjugations")
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verb");
                });

            modelBuilder.Entity("LanguaForge.API.Models.Verb", b =>
                {
                    b.Navigation("Conjugations");
                });
#pragma warning restore 612, 618
        }
    }
}
