// <auto-generated />
using LanguaForge.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LanguaForge.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260722061300_ExtendVerbModel")]
    partial class ExtendVerbModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("LanguaForge.API.Models.Verb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FrequencyRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Infinitive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIrregular")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReflexive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Verbs");
                });
#pragma warning restore 612, 618
        }
    }
}
